name: Build ESP32 Firmware

on:
  push:
    paths:
      - '**.ino'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz | tar -xz
        sudo mv arduino-cli /usr/local/bin
        arduino-cli version

    - name: Set up Arduino CLI and install ESP32 board
      run: |
        arduino-cli config init
        arduino-cli config set board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile Sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 .

    - name: Upload firmware (artifact)
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: ./build/esp32.esp32.esp32/esp32-ota.ino.bin  # ✅ 경로 수정
