name: Build ESP32 Firmware

on:
  push:
    paths:
      - '**.ino'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | bash
        echo "${HOME}/.arduino15/bin" >> $GITHUB_PATH
        echo "${HOME}/bin" >> $GITHUB_PATH
        export PATH="${HOME}/bin:${HOME}/.arduino15/bin:$PATH"
        arduino-cli config init
        arduino-cli core update-index

    - name: Install ESP32 Core
      run: |
        arduino-cli core install esp32:esp32

    - name: Compile Sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32dev firmware.ino

    - name: Upload firmware (artifact)
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: ./build/esp32.esp32.esp32dev/firmware.ino.bin
