name: Build ESP32 Firmware

on:
  push:
    paths:
      - '**.ino'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      run: |
        mkdir -p ~/.arduino15/bin
        curl -fsSL https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz | tar -xz -C ~/.arduino15/bin
        echo "$HOME/.arduino15/bin" >> $GITHUB_PATH

    - name: Set Up Arduino CLI
      run: |
        ~/.arduino15/bin/arduino-cli config init
        ~/.arduino15/bin/arduino-cli core update-index
        ~/.arduino15/bin/arduino-cli core install esp32:esp32

    - name: Compile Sketch
      run: |
        ~/.arduino15/bin/arduino-cli compile --fqbn esp32:esp32:esp32dev .

    - name: Upload firmware (artifact)
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: ./build/esp32.esp32.esp32dev/esp32-ota.ino.bin
